### ISSUE TITLE
Crash when calling 'movie_imdbid_to_title'

### ISSUE THREAD

**Issue by AndrewPaglusch** [AndrewPaglusch/PlexBot#5]
When attempting to add item with IMDBID of tt1806858

```
Failure adding movie! IMDBID: . Dumping response object...
{:movie=>false, :success=>false}
============================================================
EXCEPTION HIT!
============================================================
PRINTING INSPECT...
#<NoMethodError: undefined method `[]' for nil:NilClass>
==============================
PRINTING BACKTRACE...
/plexbot/api_movie.rb:23:in `movie_imdbid_to_title'
/plexbot/api_movie.rb:36:in `add_movie'
/plexbot/callbacks.rb:14:in `process_callback_dlm'
/plexbot/run.rb:54:in `handle_callback_query'
/plexbot/run.rb:210:in `block (2 levels) in <main>'
/usr/lib/ruby/gems/2.4.0/gems/telegram-bot-ruby-0.8.6.1/lib/telegram/bot/client.rb:38:in `block in fetch_updates'
/usr/lib/ruby/gems/2.4.0/gems/telegram-bot-ruby-0.8.6.1/lib/telegram/bot/client.rb:33:in `each'
/usr/lib/ruby/gems/2.4.0/gems/telegram-bot-ruby-0.8.6.1/lib/telegram/bot/client.rb:33:in `fetch_updates'
/usr/lib/ruby/gems/2.4.0/gems/telegram-bot-ruby-0.8.6.1/lib/telegram/bot/client.rb:25:in `listen'
/plexbot/run.rb:192:in `block in <main>'
/usr/lib/ruby/gems/2.4.0/gems/telegram-bot-ruby-0.8.6.1/lib/telegram/bot/client.rb:18:in `run'
/usr/lib/ruby/gems/2.4.0/gems/telegram-bot-ruby-0.8.6.1/lib/telegram/bot/client.rb:8:in `run'
/plexbot/run.rb:191:in `<main>'
============================================================
```

**Comment by AndrewPaglusch** [comment]
PR: #6
